import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import "dotenv/config";
import path from "node:path";
import fs from "node:fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// If OBSIDIAN_PLUGIN_DIR is set, build directly into the Obsidian vault plugin dir.
// Otherwise, build into ./dist for portability (CI / forks / other machines).
const vaultPluginDir = process.env.OBSIDIAN_PLUGIN_DIR?.trim();
const outDir = vaultPluginDir ? vaultPluginDir : path.resolve("dist");

if (!vaultPluginDir) {
  console.log("[esbuild] OBSIDIAN_PLUGIN_DIR is not set. Outputting to ./dist");
  console.log("[esbuild] Tip: create .env (see .env.example) to deploy directly to your vault.");
} else {
  console.log(`[esbuild] Outputting to plugin directory: ${vaultPluginDir}`);
}

// Ensure output directory exists
fs.mkdirSync(outDir, { recursive: true });

const outfile = path.join(outDir, "main.js");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  packages: "bundle",
  platform: "browser",
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile,
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
